// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Net struct {
	Broker               *Broker     `protobuf:"bytes,1,opt,name=broker" json:"broker,omitempty"`
	Membership           *Membership `protobuf:"bytes,2,opt,name=membership" json:"membership,omitempty"`
	Master               *Master     `protobuf:"bytes,3,opt,name=master" json:"master,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Net) Reset()         { *m = Net{} }
func (m *Net) String() string { return proto.CompactTextString(m) }
func (*Net) ProtoMessage()    {}
func (*Net) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_090257e42c7d95f0, []int{0}
}
func (m *Net) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net.Unmarshal(m, b)
}
func (m *Net) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net.Marshal(b, m, deterministic)
}
func (dst *Net) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net.Merge(dst, src)
}
func (m *Net) XXX_Size() int {
	return xxx_messageInfo_Net.Size(m)
}
func (m *Net) XXX_DiscardUnknown() {
	xxx_messageInfo_Net.DiscardUnknown(m)
}

var xxx_messageInfo_Net proto.InternalMessageInfo

func (m *Net) GetBroker() *Broker {
	if m != nil {
		return m.Broker
	}
	return nil
}

func (m *Net) GetMembership() *Membership {
	if m != nil {
		return m.Membership
	}
	return nil
}

func (m *Net) GetMaster() *Master {
	if m != nil {
		return m.Master
	}
	return nil
}

type Broker struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Broker) Reset()         { *m = Broker{} }
func (m *Broker) String() string { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()    {}
func (*Broker) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_090257e42c7d95f0, []int{1}
}
func (m *Broker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broker.Unmarshal(m, b)
}
func (m *Broker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broker.Marshal(b, m, deterministic)
}
func (dst *Broker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broker.Merge(dst, src)
}
func (m *Broker) XXX_Size() int {
	return xxx_messageInfo_Broker.Size(m)
}
func (m *Broker) XXX_DiscardUnknown() {
	xxx_messageInfo_Broker.DiscardUnknown(m)
}

var xxx_messageInfo_Broker proto.InternalMessageInfo

func (m *Broker) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Broker) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Broker) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Membership struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Membership) Reset()         { *m = Membership{} }
func (m *Membership) String() string { return proto.CompactTextString(m) }
func (*Membership) ProtoMessage()    {}
func (*Membership) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_090257e42c7d95f0, []int{2}
}
func (m *Membership) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Membership.Unmarshal(m, b)
}
func (m *Membership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Membership.Marshal(b, m, deterministic)
}
func (dst *Membership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Membership.Merge(dst, src)
}
func (m *Membership) XXX_Size() int {
	return xxx_messageInfo_Membership.Size(m)
}
func (m *Membership) XXX_DiscardUnknown() {
	xxx_messageInfo_Membership.DiscardUnknown(m)
}

var xxx_messageInfo_Membership proto.InternalMessageInfo

func (m *Membership) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type Master struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Master) Reset()         { *m = Master{} }
func (m *Master) String() string { return proto.CompactTextString(m) }
func (*Master) ProtoMessage()    {}
func (*Master) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_090257e42c7d95f0, []int{3}
}
func (m *Master) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Master.Unmarshal(m, b)
}
func (m *Master) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Master.Marshal(b, m, deterministic)
}
func (dst *Master) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Master.Merge(dst, src)
}
func (m *Master) XXX_Size() int {
	return xxx_messageInfo_Master.Size(m)
}
func (m *Master) XXX_DiscardUnknown() {
	xxx_messageInfo_Master.DiscardUnknown(m)
}

var xxx_messageInfo_Master proto.InternalMessageInfo

func (m *Master) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_090257e42c7d95f0, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Net)(nil), "pb.Net")
	proto.RegisterType((*Broker)(nil), "pb.Broker")
	proto.RegisterType((*Membership)(nil), "pb.Membership")
	proto.RegisterType((*Master)(nil), "pb.Master")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Discovery service

type DiscoveryClient interface {
	Network(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Net, error)
}

type discoveryClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryClient(cc *grpc.ClientConn) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) Network(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Net, error) {
	out := new(Net)
	err := grpc.Invoke(ctx, "/pb.Discovery/Network", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Discovery service

type DiscoveryServer interface {
	Network(context.Context, *Empty) (*Net, error)
}

func RegisterDiscoveryServer(s *grpc.Server, srv DiscoveryServer) {
	s.RegisterService(&_Discovery_serviceDesc, srv)
}

func _Discovery_Network_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).Network(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Discovery/Network",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).Network(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Network",
			Handler:    _Discovery_Network_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor_discovery_090257e42c7d95f0) }

var fileDescriptor_discovery_090257e42c7d95f0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0x03, 0x31,
	0x0c, 0x86, 0x69, 0x0b, 0x39, 0x62, 0x24, 0x90, 0x3c, 0x9d, 0xba, 0x80, 0x22, 0x86, 0x0e, 0x28,
	0x43, 0x79, 0x03, 0x04, 0x63, 0x6f, 0x88, 0x78, 0x81, 0x86, 0xb3, 0xc4, 0xa9, 0x4a, 0x13, 0x39,
	0x81, 0xaa, 0x03, 0xef, 0x8e, 0xe2, 0x96, 0x2b, 0x53, 0x37, 0xfb, 0xf7, 0xa7, 0xdf, 0xbf, 0x0d,
	0x77, 0xfd, 0x90, 0x3f, 0xe2, 0x37, 0xf1, 0xde, 0x26, 0x8e, 0x25, 0xe2, 0x34, 0x79, 0xf3, 0x03,
	0xb3, 0x8e, 0x0a, 0x1a, 0x50, 0x9e, 0xe3, 0x86, 0xb8, 0x9d, 0x3c, 0x4c, 0x16, 0x37, 0x4b, 0xb0,
	0xc9, 0xdb, 0x17, 0x51, 0xdc, 0x71, 0x82, 0x16, 0x20, 0x50, 0xf0, 0xc4, 0xf9, 0x73, 0x48, 0xed,
	0x54, 0xb8, 0xdb, 0xca, 0xad, 0x46, 0xd5, 0xfd, 0x23, 0xaa, 0x67, 0x58, 0xe7, 0x42, 0xdc, 0xce,
	0x4e, 0x9e, 0x2b, 0x51, 0xdc, 0x71, 0x62, 0xde, 0x41, 0x1d, 0xb6, 0xe0, 0x1c, 0xae, 0x69, 0xdb,
	0xa7, 0x38, 0x6c, 0x8b, 0x64, 0xd0, 0x6e, 0xec, 0x11, 0xe1, 0xf2, 0x2b, 0x13, 0xcb, 0x4e, 0xed,
	0xa4, 0xae, 0x7c, 0x5a, 0xe7, 0xbc, 0x8b, 0xdc, 0x8b, 0xbf, 0x76, 0x63, 0x6f, 0x16, 0x00, 0xa7,
	0x4c, 0xe7, 0x9c, 0xcd, 0x23, 0xa8, 0x43, 0xa2, 0xb3, 0x54, 0x03, 0x57, 0x6f, 0x21, 0x95, 0xfd,
	0xf2, 0x09, 0xf4, 0xeb, 0xdf, 0x13, 0xf1, 0x1e, 0x9a, 0x8e, 0xca, 0x2e, 0xf2, 0x06, 0x75, 0x3d,
	0x4d, 0x90, 0x79, 0x53, 0xcb, 0x8e, 0x8a, 0xb9, 0xf0, 0x4a, 0xde, 0xfc, 0xfc, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0x65, 0xc3, 0xba, 0x79, 0x01, 0x00, 0x00,
}
