// Code generated by protoc-gen-go. DO NOT EDIT.
// source: membership.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Public struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Public) Reset()         { *m = Public{} }
func (m *Public) String() string { return proto.CompactTextString(m) }
func (*Public) ProtoMessage()    {}
func (*Public) Descriptor() ([]byte, []int) {
	return fileDescriptor_membership_951a2a89b227305e, []int{0}
}
func (m *Public) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Public.Unmarshal(m, b)
}
func (m *Public) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Public.Marshal(b, m, deterministic)
}
func (dst *Public) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Public.Merge(dst, src)
}
func (m *Public) XXX_Size() int {
	return xxx_messageInfo_Public.Size(m)
}
func (m *Public) XXX_DiscardUnknown() {
	xxx_messageInfo_Public.DiscardUnknown(m)
}

var xxx_messageInfo_Public proto.InternalMessageInfo

func (m *Public) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type Account struct {
	Meta                 *AccountMeta `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	PublicKey            string       `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_membership_951a2a89b227305e, []int{1}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetMeta() *AccountMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Account) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type AccountMeta struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountMeta) Reset()         { *m = AccountMeta{} }
func (m *AccountMeta) String() string { return proto.CompactTextString(m) }
func (*AccountMeta) ProtoMessage()    {}
func (*AccountMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_membership_951a2a89b227305e, []int{2}
}
func (m *AccountMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeta.Unmarshal(m, b)
}
func (m *AccountMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeta.Marshal(b, m, deterministic)
}
func (dst *AccountMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeta.Merge(dst, src)
}
func (m *AccountMeta) XXX_Size() int {
	return xxx_messageInfo_AccountMeta.Size(m)
}
func (m *AccountMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeta proto.InternalMessageInfo

func (m *AccountMeta) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountMeta) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type Candidate struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_membership_951a2a89b227305e, []int{3}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (dst *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(dst, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Candidate) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_membership_951a2a89b227305e, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Public)(nil), "pb.Public")
	proto.RegisterType((*Account)(nil), "pb.Account")
	proto.RegisterType((*AccountMeta)(nil), "pb.AccountMeta")
	proto.RegisterType((*Candidate)(nil), "pb.Candidate")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Membership service

type MembershipClient interface {
	Register(ctx context.Context, in *Candidate, opts ...grpc.CallOption) (*Empty, error)
	Fetch(ctx context.Context, in *Public, opts ...grpc.CallOption) (*Account, error)
}

type membershipClient struct {
	cc *grpc.ClientConn
}

func NewMembershipClient(cc *grpc.ClientConn) MembershipClient {
	return &membershipClient{cc}
}

func (c *membershipClient) Register(ctx context.Context, in *Candidate, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Membership/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) Fetch(ctx context.Context, in *Public, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/pb.Membership/Fetch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Membership service

type MembershipServer interface {
	Register(context.Context, *Candidate) (*Empty, error)
	Fetch(context.Context, *Public) (*Account, error)
}

func RegisterMembershipServer(s *grpc.Server, srv MembershipServer) {
	s.RegisterService(&_Membership_serviceDesc, srv)
}

func _Membership_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Candidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Membership/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).Register(ctx, req.(*Candidate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Public)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Membership/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).Fetch(ctx, req.(*Public))
	}
	return interceptor(ctx, in, info, handler)
}

var _Membership_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Membership",
	HandlerType: (*MembershipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Membership_Register_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _Membership_Fetch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership.proto",
}

func init() { proto.RegisterFile("membership.proto", fileDescriptor_membership_951a2a89b227305e) }

var fileDescriptor_membership_951a2a89b227305e = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdb, 0x62, 0xda, 0xee, 0x0b, 0xa2, 0x0c, 0x1e, 0xa4, 0x22, 0xc8, 0x0a, 0xea, 0x29,
	0x87, 0x7a, 0x17, 0x45, 0xf4, 0x22, 0x11, 0xc9, 0xc9, 0x5b, 0xd9, 0x4d, 0x47, 0xbb, 0x98, 0x4d,
	0x96, 0x74, 0x73, 0xc8, 0xbf, 0x97, 0x6c, 0x42, 0x29, 0x3d, 0xf6, 0xb6, 0xf3, 0x66, 0xdf, 0x7b,
	0xcc, 0x87, 0x73, 0xcb, 0x56, 0x73, 0xbd, 0xdd, 0x18, 0x97, 0xb8, 0xba, 0xf2, 0x15, 0x4d, 0x9c,
	0x96, 0xf7, 0x98, 0x7e, 0x35, 0xba, 0x30, 0x39, 0x5d, 0x03, 0x2e, 0xbc, 0x56, 0x7f, 0xdc, 0x5e,
	0x8e, 0x6f, 0xc6, 0x0f, 0x22, 0x13, 0xbd, 0xf2, 0xc1, 0xad, 0x4c, 0x31, 0x7b, 0xc9, 0xf3, 0xaa,
	0x29, 0x3d, 0xdd, 0xe2, 0xc4, 0xb2, 0x57, 0xe1, 0x4f, 0xbc, 0x3c, 0x4b, 0x9c, 0x4e, 0x86, 0x55,
	0xca, 0x5e, 0x65, 0x61, 0x79, 0x10, 0x37, 0x39, 0x8c, 0x7b, 0x46, 0xbc, 0xe7, 0xa1, 0x0b, 0x44,
	0x6c, 0x95, 0x29, 0x86, 0xde, 0x7e, 0xa0, 0x2b, 0x88, 0x9f, 0xa6, 0x28, 0x56, 0xa5, 0xb2, 0x3c,
	0x44, 0xcc, 0x3b, 0xe1, 0x53, 0x59, 0x96, 0x4f, 0x10, 0xaf, 0xaa, 0x5c, 0x9b, 0xb5, 0xf2, 0x7c,
	0x8c, 0x7f, 0x86, 0xe8, 0xcd, 0x3a, 0xdf, 0x2e, 0xbf, 0x81, 0x74, 0x87, 0x86, 0xee, 0x30, 0xcf,
	0xf8, 0xd7, 0x6c, 0x3d, 0xd7, 0x74, 0xda, 0x9d, 0xb6, 0x2b, 0x59, 0x88, 0x6e, 0x0c, 0x1e, 0x39,
	0x22, 0x89, 0xe8, 0x9d, 0x7d, 0xbe, 0x21, 0x74, 0x6a, 0xcf, 0x70, 0x11, 0xef, 0xb1, 0x90, 0x23,
	0x3d, 0x0d, 0x9c, 0x1f, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x3d, 0x1a, 0x58, 0x7b, 0x01,
	0x00, 0x00,
}
