// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Endpoint struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{0}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (dst *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(dst, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type CertBlock struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertBlock) Reset()         { *m = CertBlock{} }
func (m *CertBlock) String() string { return proto.CompactTextString(m) }
func (*CertBlock) ProtoMessage()    {}
func (*CertBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{1}
}
func (m *CertBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertBlock.Unmarshal(m, b)
}
func (m *CertBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertBlock.Marshal(b, m, deterministic)
}
func (dst *CertBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertBlock.Merge(dst, src)
}
func (m *CertBlock) XXX_Size() int {
	return xxx_messageInfo_CertBlock.Size(m)
}
func (m *CertBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_CertBlock.DiscardUnknown(m)
}

var xxx_messageInfo_CertBlock proto.InternalMessageInfo

func (m *CertBlock) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type MasterBlock struct {
	Block                *Block     `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
	CertChain            *CertChain `protobuf:"bytes,4,opt,name=cert_chain,json=certChain" json:"cert_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MasterBlock) Reset()         { *m = MasterBlock{} }
func (m *MasterBlock) String() string { return proto.CompactTextString(m) }
func (*MasterBlock) ProtoMessage()    {}
func (*MasterBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{2}
}
func (m *MasterBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterBlock.Unmarshal(m, b)
}
func (m *MasterBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterBlock.Marshal(b, m, deterministic)
}
func (dst *MasterBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterBlock.Merge(dst, src)
}
func (m *MasterBlock) XXX_Size() int {
	return xxx_messageInfo_MasterBlock.Size(m)
}
func (m *MasterBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MasterBlock proto.InternalMessageInfo

func (m *MasterBlock) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *MasterBlock) GetCertChain() *CertChain {
	if m != nil {
		return m.CertChain
	}
	return nil
}

type Block struct {
	Index                int64      `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Hash                 string     `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	PrevHash             string     `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash" json:"prev_hash,omitempty"`
	Timestamp            int64      `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Tx                   string     `protobuf:"bytes,6,opt,name=tx" json:"tx,omitempty"`
	PublicKey            *PublicKey `protobuf:"bytes,7,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{3}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *Block) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type CertChain struct {
	CertChain            []*CertBlock `protobuf:"bytes,1,rep,name=cert_chain,json=certChain" json:"cert_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CertChain) Reset()         { *m = CertChain{} }
func (m *CertChain) String() string { return proto.CompactTextString(m) }
func (*CertChain) ProtoMessage()    {}
func (*CertChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{4}
}
func (m *CertChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertChain.Unmarshal(m, b)
}
func (m *CertChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertChain.Marshal(b, m, deterministic)
}
func (dst *CertChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertChain.Merge(dst, src)
}
func (m *CertChain) XXX_Size() int {
	return xxx_messageInfo_CertChain.Size(m)
}
func (m *CertChain) XXX_DiscardUnknown() {
	xxx_messageInfo_CertChain.DiscardUnknown(m)
}

var xxx_messageInfo_CertChain proto.InternalMessageInfo

func (m *CertChain) GetCertChain() []*CertBlock {
	if m != nil {
		return m.CertChain
	}
	return nil
}

type MasterChain struct {
	MasterChain          []*MasterBlock `protobuf:"bytes,1,rep,name=master_chain,json=masterChain" json:"master_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MasterChain) Reset()         { *m = MasterChain{} }
func (m *MasterChain) String() string { return proto.CompactTextString(m) }
func (*MasterChain) ProtoMessage()    {}
func (*MasterChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{5}
}
func (m *MasterChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterChain.Unmarshal(m, b)
}
func (m *MasterChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterChain.Marshal(b, m, deterministic)
}
func (dst *MasterChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterChain.Merge(dst, src)
}
func (m *MasterChain) XXX_Size() int {
	return xxx_messageInfo_MasterChain.Size(m)
}
func (m *MasterChain) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterChain.DiscardUnknown(m)
}

var xxx_messageInfo_MasterChain proto.InternalMessageInfo

func (m *MasterChain) GetMasterChain() []*MasterBlock {
	if m != nil {
		return m.MasterChain
	}
	return nil
}

type Cert struct {
	Id                   string       `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Meta                 *CertMeta    `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
	Issuer               *Participant `protobuf:"bytes,4,opt,name=issuer" json:"issuer,omitempty"`
	Recipient            *Participant `protobuf:"bytes,5,opt,name=recipient" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Cert) Reset()         { *m = Cert{} }
func (m *Cert) String() string { return proto.CompactTextString(m) }
func (*Cert) ProtoMessage()    {}
func (*Cert) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{6}
}
func (m *Cert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cert.Unmarshal(m, b)
}
func (m *Cert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cert.Marshal(b, m, deterministic)
}
func (dst *Cert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cert.Merge(dst, src)
}
func (m *Cert) XXX_Size() int {
	return xxx_messageInfo_Cert.Size(m)
}
func (m *Cert) XXX_DiscardUnknown() {
	xxx_messageInfo_Cert.DiscardUnknown(m)
}

var xxx_messageInfo_Cert proto.InternalMessageInfo

func (m *Cert) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cert) GetMeta() *CertMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Cert) GetIssuer() *Participant {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *Cert) GetRecipient() *Participant {
	if m != nil {
		return m.Recipient
	}
	return nil
}

type Participant struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PublicKey            *PublicKey `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	Signature            string     `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{7}
}
func (m *Participant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participant.Unmarshal(m, b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
}
func (dst *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(dst, src)
}
func (m *Participant) XXX_Size() int {
	return xxx_messageInfo_Participant.Size(m)
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Participant) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Participant) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type CertMeta struct {
	Title                string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertMeta) Reset()         { *m = CertMeta{} }
func (m *CertMeta) String() string { return proto.CompactTextString(m) }
func (*CertMeta) ProtoMessage()    {}
func (*CertMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{8}
}
func (m *CertMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertMeta.Unmarshal(m, b)
}
func (m *CertMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertMeta.Marshal(b, m, deterministic)
}
func (dst *CertMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertMeta.Merge(dst, src)
}
func (m *CertMeta) XXX_Size() int {
	return xxx_messageInfo_CertMeta.Size(m)
}
func (m *CertMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CertMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CertMeta proto.InternalMessageInfo

func (m *CertMeta) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CertMeta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CertMeta) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PublicKey struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{9}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{10}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type BrokerOpts struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerOpts) Reset()         { *m = BrokerOpts{} }
func (m *BrokerOpts) String() string { return proto.CompactTextString(m) }
func (*BrokerOpts) ProtoMessage()    {}
func (*BrokerOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{11}
}
func (m *BrokerOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerOpts.Unmarshal(m, b)
}
func (m *BrokerOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerOpts.Marshal(b, m, deterministic)
}
func (dst *BrokerOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerOpts.Merge(dst, src)
}
func (m *BrokerOpts) XXX_Size() int {
	return xxx_messageInfo_BrokerOpts.Size(m)
}
func (m *BrokerOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerOpts.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerOpts proto.InternalMessageInfo

func (m *BrokerOpts) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *BrokerOpts) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BrokerOpts) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InitNetworkOpts struct {
	Broker               *BrokerOpts `protobuf:"bytes,1,opt,name=broker" json:"broker,omitempty"`
	Membership           string      `protobuf:"bytes,2,opt,name=membership" json:"membership,omitempty"`
	Master               string      `protobuf:"bytes,3,opt,name=master" json:"master,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InitNetworkOpts) Reset()         { *m = InitNetworkOpts{} }
func (m *InitNetworkOpts) String() string { return proto.CompactTextString(m) }
func (*InitNetworkOpts) ProtoMessage()    {}
func (*InitNetworkOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{12}
}
func (m *InitNetworkOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitNetworkOpts.Unmarshal(m, b)
}
func (m *InitNetworkOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitNetworkOpts.Marshal(b, m, deterministic)
}
func (dst *InitNetworkOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitNetworkOpts.Merge(dst, src)
}
func (m *InitNetworkOpts) XXX_Size() int {
	return xxx_messageInfo_InitNetworkOpts.Size(m)
}
func (m *InitNetworkOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_InitNetworkOpts.DiscardUnknown(m)
}

var xxx_messageInfo_InitNetworkOpts proto.InternalMessageInfo

func (m *InitNetworkOpts) GetBroker() *BrokerOpts {
	if m != nil {
		return m.Broker
	}
	return nil
}

func (m *InitNetworkOpts) GetMembership() string {
	if m != nil {
		return m.Membership
	}
	return ""
}

func (m *InitNetworkOpts) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

type Member struct {
	PublicKey            *PublicKey  `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	PrivateKey           []byte      `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Meta                 *MemberMeta `protobuf:"bytes,4,opt,name=meta" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{13}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetPublicKey() *PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Member) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *Member) GetMeta() *MemberMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MemberMeta struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberMeta) Reset()         { *m = MemberMeta{} }
func (m *MemberMeta) String() string { return proto.CompactTextString(m) }
func (*MemberMeta) ProtoMessage()    {}
func (*MemberMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_b08ea9208606fd23, []int{14}
}
func (m *MemberMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberMeta.Unmarshal(m, b)
}
func (m *MemberMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberMeta.Marshal(b, m, deterministic)
}
func (dst *MemberMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberMeta.Merge(dst, src)
}
func (m *MemberMeta) XXX_Size() int {
	return xxx_messageInfo_MemberMeta.Size(m)
}
func (m *MemberMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MemberMeta proto.InternalMessageInfo

func (m *MemberMeta) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MemberMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "pb.endpoint")
	proto.RegisterType((*CertBlock)(nil), "pb.cert_block")
	proto.RegisterType((*MasterBlock)(nil), "pb.master_block")
	proto.RegisterType((*Block)(nil), "pb.block")
	proto.RegisterType((*CertChain)(nil), "pb.cert_chain")
	proto.RegisterType((*MasterChain)(nil), "pb.master_chain")
	proto.RegisterType((*Cert)(nil), "pb.cert")
	proto.RegisterType((*Participant)(nil), "pb.participant")
	proto.RegisterType((*CertMeta)(nil), "pb.cert_meta")
	proto.RegisterType((*PublicKey)(nil), "pb.public_key")
	proto.RegisterType((*Empty)(nil), "pb.empty")
	proto.RegisterType((*BrokerOpts)(nil), "pb.broker_opts")
	proto.RegisterType((*InitNetworkOpts)(nil), "pb.init_network_opts")
	proto.RegisterType((*Member)(nil), "pb.member")
	proto.RegisterType((*MemberMeta)(nil), "pb.member_meta")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoveryClient interface {
	InitNode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InitNetworkOpts, error)
	InitMaster(ctx context.Context, in *Endpoint, opts ...grpc.CallOption) (*BrokerOpts, error)
	InitMembership(ctx context.Context, in *Endpoint, opts ...grpc.CallOption) (*InitNetworkOpts, error)
}

type discoveryClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryClient(cc *grpc.ClientConn) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) InitNode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InitNetworkOpts, error) {
	out := new(InitNetworkOpts)
	err := c.cc.Invoke(ctx, "/pb.discovery/init_node", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) InitMaster(ctx context.Context, in *Endpoint, opts ...grpc.CallOption) (*BrokerOpts, error) {
	out := new(BrokerOpts)
	err := c.cc.Invoke(ctx, "/pb.discovery/init_master", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) InitMembership(ctx context.Context, in *Endpoint, opts ...grpc.CallOption) (*InitNetworkOpts, error) {
	out := new(InitNetworkOpts)
	err := c.cc.Invoke(ctx, "/pb.discovery/init_membership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Discovery service

type DiscoveryServer interface {
	InitNode(context.Context, *Empty) (*InitNetworkOpts, error)
	InitMaster(context.Context, *Endpoint) (*BrokerOpts, error)
	InitMembership(context.Context, *Endpoint) (*InitNetworkOpts, error)
}

func RegisterDiscoveryServer(s *grpc.Server, srv DiscoveryServer) {
	s.RegisterService(&_Discovery_serviceDesc, srv)
}

func _Discovery_InitNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).InitNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.discovery/InitNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).InitNode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_InitMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Endpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).InitMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.discovery/InitMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).InitMaster(ctx, req.(*Endpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_InitMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Endpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).InitMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.discovery/InitMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).InitMembership(ctx, req.(*Endpoint))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "init_node",
			Handler:    _Discovery_InitNode_Handler,
		},
		{
			MethodName: "init_master",
			Handler:    _Discovery_InitMaster_Handler,
		},
		{
			MethodName: "init_membership",
			Handler:    _Discovery_InitMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	ProposeCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*Empty, error)
	InitNode(ctx context.Context, in *PublicKey, opts ...grpc.CallOption) (*MasterChain, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) ProposeCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.master/propose_cert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) InitNode(ctx context.Context, in *PublicKey, opts ...grpc.CallOption) (*MasterChain, error) {
	out := new(MasterChain)
	err := c.cc.Invoke(ctx, "/pb.master/init_node", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Master service

type MasterServer interface {
	ProposeCert(context.Context, *Cert) (*Empty, error)
	InitNode(context.Context, *PublicKey) (*MasterChain, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_ProposeCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).ProposeCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.master/ProposeCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).ProposeCert(ctx, req.(*Cert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_InitNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).InitNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.master/InitNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).InitNode(ctx, req.(*PublicKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "propose_cert",
			Handler:    _Master_ProposeCert_Handler,
		},
		{
			MethodName: "init_node",
			Handler:    _Master_InitNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

// MembershipClient is the client API for Membership service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MembershipClient interface {
	ProposeMember(ctx context.Context, in *MemberMeta, opts ...grpc.CallOption) (*PublicKey, error)
	FetchMember(ctx context.Context, in *PublicKey, opts ...grpc.CallOption) (*Member, error)
	SignCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*Empty, error)
}

type membershipClient struct {
	cc *grpc.ClientConn
}

func NewMembershipClient(cc *grpc.ClientConn) MembershipClient {
	return &membershipClient{cc}
}

func (c *membershipClient) ProposeMember(ctx context.Context, in *MemberMeta, opts ...grpc.CallOption) (*PublicKey, error) {
	out := new(PublicKey)
	err := c.cc.Invoke(ctx, "/pb.membership/propose_member", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) FetchMember(ctx context.Context, in *PublicKey, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/pb.membership/fetch_member", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipClient) SignCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.membership/sign_cert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Membership service

type MembershipServer interface {
	ProposeMember(context.Context, *MemberMeta) (*PublicKey, error)
	FetchMember(context.Context, *PublicKey) (*Member, error)
	SignCert(context.Context, *Cert) (*Empty, error)
}

func RegisterMembershipServer(s *grpc.Server, srv MembershipServer) {
	s.RegisterService(&_Membership_serviceDesc, srv)
}

func _Membership_ProposeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).ProposeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.membership/ProposeMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).ProposeMember(ctx, req.(*MemberMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_FetchMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).FetchMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.membership/FetchMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).FetchMember(ctx, req.(*PublicKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Membership_SignCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServer).SignCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.membership/SignCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServer).SignCert(ctx, req.(*Cert))
	}
	return interceptor(ctx, in, info, handler)
}

var _Membership_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.membership",
	HandlerType: (*MembershipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "propose_member",
			Handler:    _Membership_ProposeMember_Handler,
		},
		{
			MethodName: "fetch_member",
			Handler:    _Membership_FetchMember_Handler,
		},
		{
			MethodName: "sign_cert",
			Handler:    _Membership_SignCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_pb_b08ea9208606fd23) }

var fileDescriptor_pb_b08ea9208606fd23 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0x8e, 0xf3, 0x6a, 0x7d, 0x9c, 0xdb, 0xde, 0x3b, 0xba, 0xf7, 0x2a, 0x0a, 0x8f, 0x86, 0x41,
	0xd0, 0x4a, 0xd0, 0x20, 0xa5, 0x0b, 0x90, 0x58, 0x76, 0x83, 0xc4, 0xce, 0x3b, 0x36, 0x04, 0x3f,
	0x0e, 0x64, 0x94, 0xd8, 0x1e, 0xcd, 0x4c, 0xda, 0x66, 0xc1, 0x8f, 0x40, 0xfc, 0x07, 0x36, 0xfc,
	0x49, 0x34, 0x0f, 0xc7, 0x13, 0x03, 0x05, 0x76, 0xe7, 0x7c, 0x73, 0xe6, 0x3c, 0xbe, 0xef, 0x8c,
	0x0d, 0x87, 0x3c, 0x9d, 0x71, 0x51, 0xa9, 0x8a, 0x74, 0x79, 0x4a, 0x1f, 0xc3, 0x21, 0x96, 0x39,
	0xaf, 0x58, 0xa9, 0xc8, 0xa4, 0xb1, 0xc7, 0xc1, 0x34, 0x38, 0x0b, 0xe3, 0x9d, 0x4f, 0xcf, 0x01,
	0x32, 0x14, 0x6a, 0x91, 0xae, 0xab, 0x6c, 0x45, 0x4e, 0x60, 0x60, 0x0c, 0x13, 0x16, 0xcd, 0xc3,
	0x19, 0x4f, 0x67, 0x06, 0x88, 0x2d, 0x4e, 0xdf, 0xc2, 0xa8, 0x48, 0xa4, 0x42, 0xf1, 0x9b, 0x17,
	0x48, 0x9d, 0x3f, 0x5b, 0x26, 0xac, 0x1c, 0xf7, 0x4d, 0xd4, 0x91, 0x8e, 0x6a, 0xd0, 0x38, 0xd4,
	0xf6, 0xa5, 0x36, 0xe9, 0xd7, 0xc0, 0x25, 0x24, 0xff, 0xc2, 0x80, 0x95, 0x39, 0xde, 0x8c, 0xbb,
	0xd3, 0xe0, 0xac, 0x17, 0x5b, 0x87, 0x10, 0xe8, 0x2f, 0x13, 0xb9, 0x1c, 0xf7, 0xcc, 0x18, 0xc6,
	0x26, 0x77, 0x20, 0xe4, 0x02, 0xaf, 0x16, 0xe6, 0xa0, 0x6f, 0xe7, 0xd3, 0xc0, 0x2b, 0x7d, 0x78,
	0x17, 0x42, 0xc5, 0x0a, 0x94, 0x2a, 0x29, 0xf8, 0x78, 0x60, 0x52, 0x35, 0x00, 0x39, 0x82, 0xae,
	0xba, 0x19, 0x0f, 0xcd, 0x9d, 0xae, 0xba, 0xd1, 0xdd, 0xf2, 0x4d, 0xba, 0x66, 0xd9, 0x62, 0x85,
	0xdb, 0xf1, 0x41, 0xd3, 0x6d, 0x83, 0xc6, 0xa1, 0xb5, 0x5f, 0xe3, 0x96, 0xbe, 0xf4, 0x87, 0x6b,
	0x8d, 0x1a, 0x4c, 0x7b, 0x7b, 0xa3, 0x5a, 0x56, 0xbc, 0x51, 0x2f, 0x77, 0x54, 0xda, 0xeb, 0x17,
	0xfb, 0xbe, 0x4b, 0xf0, 0xb7, 0x4e, 0xe0, 0x53, 0x1e, 0x47, 0xd6, 0xb3, 0x49, 0x3e, 0x05, 0xd0,
	0xd7, 0x29, 0xf5, 0x24, 0x2c, 0x37, 0x5c, 0x85, 0x71, 0x97, 0xe5, 0xe4, 0x01, 0xf4, 0x0b, 0x54,
	0x89, 0x21, 0x2a, 0x9a, 0xff, 0xb5, 0x6b, 0x43, 0x83, 0xb1, 0x39, 0x22, 0xa7, 0x30, 0x64, 0x52,
	0x6e, 0x50, 0x38, 0x59, 0x8e, 0xcd, 0xa0, 0x89, 0x50, 0x2c, 0x63, 0x3c, 0x29, 0x55, 0xec, 0x8e,
	0xc9, 0x39, 0x84, 0x02, 0x33, 0xc6, 0x19, 0x96, 0xca, 0x70, 0xf8, 0x83, 0xd8, 0x26, 0x82, 0x96,
	0x10, 0x79, 0x27, 0x5a, 0xb2, 0x32, 0x29, 0xd0, 0x6d, 0x9e, 0xb1, 0x5b, 0x3c, 0x77, 0x7f, 0xc1,
	0xb3, 0x16, 0x51, 0xb2, 0x0f, 0x65, 0xa2, 0x36, 0x02, 0x9d, 0xf4, 0x0d, 0x40, 0x13, 0x08, 0x77,
	0xa3, 0xe9, 0xb5, 0x51, 0x4c, 0xad, 0xeb, 0x72, 0xd6, 0x21, 0x53, 0x88, 0x72, 0x94, 0x99, 0x60,
	0x5c, 0xb1, 0xaa, 0x74, 0x34, 0xf9, 0xd0, 0xfe, 0x9e, 0xf4, 0x5a, 0x7b, 0x42, 0x9f, 0xf8, 0xfd,
	0x92, 0x7b, 0x7b, 0xdd, 0xdb, 0x42, 0xde, 0x56, 0x1c, 0xc0, 0x00, 0x0b, 0xae, 0xb6, 0xf4, 0x0d,
	0x44, 0xa9, 0xa8, 0x56, 0x28, 0x16, 0x15, 0x57, 0xf2, 0xb6, 0x67, 0xa8, 0x49, 0xda, 0x48, 0x14,
	0xae, 0x33, 0x63, 0xeb, 0x78, 0x9e, 0x48, 0x79, 0x5d, 0x89, 0xdc, 0x0d, 0xbd, 0xf3, 0xa9, 0x82,
	0x7f, 0x58, 0xc9, 0xd4, 0xa2, 0x44, 0x75, 0x5d, 0x89, 0x95, 0x2d, 0x70, 0x0a, 0x43, 0x5b, 0xcf,
	0xbd, 0x46, 0x23, 0x92, 0xd7, 0x41, 0xec, 0x8e, 0xc9, 0x7d, 0x80, 0x02, 0x8b, 0x14, 0x85, 0x5c,
	0x32, 0xee, 0x6a, 0x7a, 0x08, 0xf9, 0x1f, 0x86, 0x76, 0xc9, 0x5c, 0x5d, 0xe7, 0xd1, 0x8f, 0x30,
	0xb4, 0x51, 0x7f, 0x2a, 0xe0, 0x09, 0x44, 0x5c, 0xb0, 0xab, 0x44, 0xa1, 0x89, 0xd7, 0x59, 0x47,
	0x31, 0x38, 0x48, 0x07, 0x3c, 0x74, 0xeb, 0xea, 0x6d, 0xa2, 0xad, 0xe4, 0x2d, 0x2c, 0x7d, 0x0e,
	0x91, 0x07, 0x6a, 0xa9, 0xb1, 0x48, 0xd8, 0xba, 0x96, 0xda, 0x38, 0xbb, 0x75, 0xeb, 0x36, 0xeb,
	0x36, 0xff, 0x12, 0x40, 0x98, 0x33, 0x99, 0x55, 0x57, 0x28, 0xb6, 0xe4, 0x19, 0x84, 0x96, 0xbb,
	0x2a, 0x47, 0x62, 0xbe, 0x58, 0x46, 0xae, 0xc9, 0x7f, 0xda, 0xfc, 0x8e, 0x55, 0xda, 0x21, 0x33,
	0x88, 0x0c, 0x6c, 0x59, 0x20, 0x23, 0x73, 0xc5, 0x29, 0x37, 0x69, 0x93, 0x4c, 0x3b, 0xe4, 0x05,
	0x1c, 0xdb, 0xf8, 0x86, 0xd1, 0xfd, 0x3b, 0x3f, 0xab, 0x34, 0x7f, 0x57, 0x13, 0x4f, 0x1e, 0xc1,
	0x88, 0x8b, 0x8a, 0x57, 0x12, 0x17, 0xe6, 0x7d, 0x1f, 0xd6, 0x2f, 0x78, 0xd2, 0x74, 0x4c, 0x3b,
	0xfb, 0xb3, 0xb4, 0x04, 0x98, 0xf8, 0xdf, 0x0e, 0xf3, 0x4d, 0xa1, 0x9d, 0xf9, 0xe7, 0xc0, 0xd7,
	0x9e, 0x5c, 0xc0, 0x51, 0x5d, 0xc6, 0x29, 0xdb, 0xe6, 0x7e, 0xd2, 0xca, 0x4a, 0x3b, 0xe4, 0x29,
	0x8c, 0xde, 0xa3, 0xca, 0x96, 0xf5, 0x95, 0x76, 0x5d, 0x68, 0x52, 0xd0, 0x0e, 0xa1, 0xf6, 0xf1,
	0xde, 0x36, 0x46, 0x3a, 0x34, 0x3f, 0xae, 0x8b, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xa6,
	0x19, 0x7f, 0xc4, 0x06, 0x00, 0x00,
}
